package com.election.mapping;// Generated Dec 28, 2017 3:24:17 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CandidateList generated by hbm2java
 */
@Entity
@Table(name="candidate_list"
    ,catalog="elect_survey"
)
public class CandidateList  implements java.io.Serializable {


     private Integer id;
     private Candidate candidate;
     private Ward ward;
     private String type;

    public CandidateList() {
    }

    public CandidateList(Candidate candidate, Ward ward, String type) {
       this.candidate = candidate;
       this.ward = ward;
       this.type = type;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="candidate_id")
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ward_code")
    public Ward getWard() {
        return this.ward;
    }
    
    public void setWard(Ward ward) {
        this.ward = ward;
    }

    
    @Column(name="type", length=10)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


