package com.election.mapping;
// Generated Dec 24, 2017 10:28:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Candidate generated by hbm2java
 */
@Entity
@Table(name="candidate"
    ,catalog="ELCT_Survey"
)
public class Candidate  implements java.io.Serializable {


     private int candidateId;
     private Party party;
     private String wardCode;
     private String name;
     private String nic;
     private String contactNo;
     private String address;
     private String gender;
     private String youth;
     private String username;
     private String password;
     private String oldPassword;
     private String status;
     private Set<CandidateList> candidateLists = new HashSet(0);
     private Set<ElectionSurvery> electionSurveries = new HashSet(0);

    public Candidate() {
    }

	
    public Candidate(int candidateId, Party party) {
        this.candidateId = candidateId;
        this.party = party;
    }
    public Candidate(int candidateId, Party party, String wardCode, String name, String nic, String contactNo, String address, String gender, String youth, String username, String password, String oldPassword, String status, Set<CandidateList> candidateLists, Set<ElectionSurvery> electionSurveries) {
       this.candidateId = candidateId;
       this.party = party;
       this.wardCode = wardCode;
       this.name = name;
       this.nic = nic;
       this.contactNo = contactNo;
       this.address = address;
       this.gender = gender;
       this.youth = youth;
       this.username = username;
       this.password = password;
       this.oldPassword = oldPassword;
       this.status = status;
       this.candidateLists = candidateLists;
       this.electionSurveries = electionSurveries;
    }
   
     @Id 

    
    @Column(name="candidate_id", unique=true, nullable=false)
    public int getCandidateId() {
        return this.candidateId;
    }
    
    public void setCandidateId(int candidateId) {
        this.candidateId = candidateId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="party_code", nullable=false)
    public Party getParty() {
        return this.party;
    }
    
    public void setParty(Party party) {
        this.party = party;
    }

    
    @Column(name="ward_code", length=45)
    public String getWardCode() {
        return this.wardCode;
    }
    
    public void setWardCode(String wardCode) {
        this.wardCode = wardCode;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="nic", length=45)
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }

    
    @Column(name="contact_no", length=45)
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    
    @Column(name="address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="gender", length=45)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="youth", length=45)
    public String getYouth() {
        return this.youth;
    }
    
    public void setYouth(String youth) {
        this.youth = youth;
    }

    
    @Column(name="username", length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="old_password", length=45)
    public String getOldPassword() {
        return this.oldPassword;
    }
    
    public void setOldPassword(String oldPassword) {
        this.oldPassword = oldPassword;
    }

    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidate")
    public Set<CandidateList> getCandidateLists() {
        return this.candidateLists;
    }
    
    public void setCandidateLists(Set<CandidateList> candidateLists) {
        this.candidateLists = candidateLists;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidate")
    public Set<ElectionSurvery> getElectionSurveries() {
        return this.electionSurveries;
    }
    
    public void setElectionSurveries(Set<ElectionSurvery> electionSurveries) {
        this.electionSurveries = electionSurveries;
    }




}


