package com.election.mapping;// Generated Jan 15, 2018 9:03:36 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CandidateList generated by hbm2java
 */
@Entity
@Table(name="candidate_list"
    
)
public class CandidateList  implements java.io.Serializable {


     private int id;
     private Candidate candidate;
     private Ward ward;
     private String type;

    public CandidateList() {
    }

	
    public CandidateList(int id) {
        this.id = id;
    }
    public CandidateList(int id, Candidate candidate, Ward ward, String type) {
       this.id = id;
       this.candidate = candidate;
       this.ward = ward;
       this.type = type;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="candidate_id")
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ward_code")
    public Ward getWard() {
        return this.ward;
    }
    
    public void setWard(Ward ward) {
        this.ward = ward;
    }

    
    @Column(name="type", length=10)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


