package com.election.mapping;
// Generated Dec 24, 2017 10:28:34 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CandidateList generated by hbm2java
 */
@Entity
@Table(name="candidate_list"
    ,catalog="ELCT_Survey"
)
public class CandidateList  implements java.io.Serializable {


     private int id;
     private Candidate candidate;
     private String wardCode;
     private String type;

    public CandidateList() {
    }

	
    public CandidateList(int id) {
        this.id = id;
    }
    public CandidateList(int id, Candidate candidate, String wardCode, String type) {
       this.id = id;
       this.candidate = candidate;
       this.wardCode = wardCode;
       this.type = type;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="candidate_id")
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

    
    @Column(name="ward_code", length=45)
    public String getWardCode() {
        return this.wardCode;
    }
    
    public void setWardCode(String wardCode) {
        this.wardCode = wardCode;
    }

    
    @Column(name="type", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


