package com.election.mapping;
// Generated Jan 7, 2018 2:28:48 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ElectionSurveyInfo generated by hbm2java
 */
@Entity
@Table(name="election_survey_info"
    
)
public class ElectionSurveyInfo  implements java.io.Serializable {


     private Integer id;
     private ElectionSurvey electionSurvey;
     private ServiceList serviceList;

    public ElectionSurveyInfo() {
    }

    public ElectionSurveyInfo(ElectionSurvey electionSurvey, ServiceList serviceList) {
       this.electionSurvey = electionSurvey;
       this.serviceList = serviceList;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="survey_id")
    public ElectionSurvey getElectionSurvey() {
        return this.electionSurvey;
    }
    
    public void setElectionSurvey(ElectionSurvey electionSurvey) {
        this.electionSurvey = electionSurvey;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="service_list_id")
    public ServiceList getServiceList() {
        return this.serviceList;
    }
    
    public void setServiceList(ServiceList serviceList) {
        this.serviceList = serviceList;
    }




}


