package com.election.mapping;// Generated Dec 28, 2017 3:24:17 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ElectionSurvey generated by hbm2java
 */
@Entity
@Table(name="election_survey"
    ,catalog="elct_survey"
)
public class ElectionSurvey  implements java.io.Serializable {


     private int id;
     private Candidate candidate;
     private ServiceList serviceList;

    public ElectionSurvey() {
    }

	
    public ElectionSurvey(int id) {
        this.id = id;
    }
    public ElectionSurvey(int id, Candidate candidate, ServiceList serviceList) {
       this.id = id;
       this.candidate = candidate;
       this.serviceList = serviceList;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="candidate_id")
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="service_list_id")
    public ServiceList getServiceList() {
        return this.serviceList;
    }
    
    public void setServiceList(ServiceList serviceList) {
        this.serviceList = serviceList;
    }




}


