package com.election.mapping;
// Generated Dec 24, 2017 10:28:34 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ElectionSurvery generated by hbm2java
 */
@Entity
@Table(name="election_survery"
    ,catalog="ELCT_Survey"
)
public class ElectionSurvery  implements java.io.Serializable {


     private int id;
     private Candidate candidate;
     private ServiceList serviceList;

    public ElectionSurvery() {
    }

	
    public ElectionSurvery(int id) {
        this.id = id;
    }
    public ElectionSurvery(int id, Candidate candidate, ServiceList serviceList) {
       this.id = id;
       this.candidate = candidate;
       this.serviceList = serviceList;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="survey_list_id")
    public ServiceList getServiceList() {
        return this.serviceList;
    }
    
    public void setServiceList(ServiceList serviceList) {
        this.serviceList = serviceList;
    }




}


