package com.election.mapping;// Generated Jan 15, 2018 9:03:36 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ElectionSurvey generated by hbm2java
 */
@Entity
@Table(name="election_survey"
    ,catalog="election_survey"
)
public class ElectionSurvey  implements java.io.Serializable {


     private int id;
     private int userId;
     private char isParty;
     private Date createdTime;
     private Set<ElectionSurveyInfo> electionSurveyInfos = new HashSet(0);

    public ElectionSurvey() {
    }

	
    public ElectionSurvey(int id, int userId, char isParty) {
        this.id = id;
        this.userId = userId;
        this.isParty = isParty;
    }
    public ElectionSurvey(int id, int userId, char isParty, Date createdTime, Set<ElectionSurveyInfo> electionSurveyInfos) {
       this.id = id;
       this.userId = userId;
       this.isParty = isParty;
       this.createdTime = createdTime;
       this.electionSurveyInfos = electionSurveyInfos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="is_party", nullable=false, length=1)
    public char getIsParty() {
        return this.isParty;
    }
    
    public void setIsParty(char isParty) {
        this.isParty = isParty;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="electionSurvey")
    public Set<ElectionSurveyInfo> getElectionSurveyInfos() {
        return this.electionSurveyInfos;
    }
    
    public void setElectionSurveyInfos(Set<ElectionSurveyInfo> electionSurveyInfos) {
        this.electionSurveyInfos = electionSurveyInfos;
    }




}


