package com.election.mapping;
// Generated Jan 7, 2018 2:28:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ElectionSurvey generated by hbm2java
 */
@Entity
@Table(name="election_survey"
    ,catalog="elect_survey"
)
public class ElectionSurvey  implements java.io.Serializable {


     private int id;
     private Candidate candidate;
     private Set<ElectionSurveyInfo> electionSurveyInfos = new HashSet(0);

    public ElectionSurvey() {
    }

	
    public ElectionSurvey(int id) {
        this.id = id;
    }
    public ElectionSurvey(int id, Candidate candidate, Set<ElectionSurveyInfo> electionSurveyInfos) {
       this.id = id;
       this.candidate = candidate;
       this.electionSurveyInfos = electionSurveyInfos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="candidate_id")
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="electionSurvey")
    public Set<ElectionSurveyInfo> getElectionSurveyInfos() {
        return this.electionSurveyInfos;
    }
    
    public void setElectionSurveyInfos(Set<ElectionSurveyInfo> electionSurveyInfos) {
        this.electionSurveyInfos = electionSurveyInfos;
    }




}


