package com.election.mapping;
// Generated Dec 24, 2017 10:28:34 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PartyLa generated by hbm2java
 */
@Entity
@Table(name="party_la"
    ,catalog="ELCT_Survey"
)
public class PartyLa  implements java.io.Serializable {


     private int id;
     private Party party;
     private String laCode;
     private String contactNo;
     private String address;
     private String username;
     private String password;
     private String oldPassword;
     private String status;

    public PartyLa() {
    }

	
    public PartyLa(int id) {
        this.id = id;
    }
    public PartyLa(int id, Party party, String laCode, String contactNo, String address, String username, String password, String oldPassword, String status) {
       this.id = id;
       this.party = party;
       this.laCode = laCode;
       this.contactNo = contactNo;
       this.address = address;
       this.username = username;
       this.password = password;
       this.oldPassword = oldPassword;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="party_code")
    public Party getParty() {
        return this.party;
    }
    
    public void setParty(Party party) {
        this.party = party;
    }

    
    @Column(name="la_code", length=45)
    public String getLaCode() {
        return this.laCode;
    }
    
    public void setLaCode(String laCode) {
        this.laCode = laCode;
    }

    
    @Column(name="contact_no", length=45)
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    
    @Column(name="address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="username", length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="old_password", length=45)
    public String getOldPassword() {
        return this.oldPassword;
    }
    
    public void setOldPassword(String oldPassword) {
        this.oldPassword = oldPassword;
    }

    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


