package com.election.mapping;// Generated Dec 28, 2017 3:24:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ServiceList generated by hbm2java
 */
@Entity
@Table(name="service_list"
    ,catalog="elect_survey"
)
public class ServiceList  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String name;
     private String description;
     private String status;
     private Set<ElectionSurvey> electionSurveys = new HashSet(0);

    public ServiceList() {
    }

    public ServiceList(String code, String name, String description, String status, Set<ElectionSurvey> electionSurveys) {
       this.code = code;
       this.name = name;
       this.description = description;
       this.status = status;
       this.electionSurveys = electionSurveys;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="serviceList")
    public Set<ElectionSurvey> getElectionSurveys() {
        return this.electionSurveys;
    }
    
    public void setElectionSurveys(Set<ElectionSurvey> electionSurveys) {
        this.electionSurveys = electionSurveys;
    }




}


