package com.election.mapping;// Generated Jan 15, 2018 9:03:36 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Voting generated by hbm2java
 */
@Entity
@Table(name="voting"
    ,catalog="election_survey"
)
public class Voting  implements java.io.Serializable {


     private int id;
     private LocalAuthority localAuthority;
     private Ward ward;
     private String vote;
     private Date datetime;
     private String userId;
     private String userType;

    public Voting() {
    }

	
    public Voting(int id) {
        this.id = id;
    }
    public Voting(int id, LocalAuthority localAuthority, Ward ward, String vote, Date datetime, String userId, String userType) {
       this.id = id;
       this.localAuthority = localAuthority;
       this.ward = ward;
       this.vote = vote;
       this.datetime = datetime;
       this.userId = userId;
       this.userType = userType;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="la_code")
    public LocalAuthority getLocalAuthority() {
        return this.localAuthority;
    }
    
    public void setLocalAuthority(LocalAuthority localAuthority) {
        this.localAuthority = localAuthority;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ward_code")
    public Ward getWard() {
        return this.ward;
    }
    
    public void setWard(Ward ward) {
        this.ward = ward;
    }

    
    @Column(name="vote")
    public String getVote() {
        return this.vote;
    }
    
    public void setVote(String vote) {
        this.vote = vote;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datetime", length=19)
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    
    @Column(name="user_id")
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="user_type", length=10)
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }




}


