package com.election.mapping;
// Generated Jan 7, 2018 2:28:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Voting generated by hbm2java
 */
@Entity
@Table(name="voting"
    ,catalog="elect_survey"
)
public class Voting  implements java.io.Serializable {


     private Integer id;
     private LocalAuthority localAuthority;
     private Ward ward;
     private String vote;
     private Date datetime;
     private String userId;
     private String userType;

    public Voting() {
    }

    public Voting(LocalAuthority localAuthority, Ward ward, String vote, Date datetime, String userId,String userType) {
       this.localAuthority = localAuthority;
       this.ward = ward;
       this.vote = vote;
       this.datetime = datetime;
       this.userId = userId;
       this.userType = userType;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="la_code")
    public LocalAuthority getLocalAuthority() {
        return this.localAuthority;
    }
    
    public void setLocalAuthority(LocalAuthority localAuthority) {
        this.localAuthority = localAuthority;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ward_code")
    public Ward getWard() {
        return this.ward;
    }
    
    public void setWard(Ward ward) {
        this.ward = ward;
    }

    
    @Column(name="vote")
    public String getVote() {
        return this.vote;
    }
    
    public void setVote(String vote) {
        this.vote = vote;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datetime", length=19)
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    
    @Column(name="user_id")
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    @Column(name="user_type")
    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }
   

}


